// Module2_FrontendDev/handson_08/src/App.vue
<template>
  <div class="app-container">
    <Header />
    <main>
      <!-- Task 113: RouterView Outlet -->
      <RouterView />
    </main>
    <footer class="site-footer">
      <p>&copy; 2026 Student Portal Vue 3 Application | Composition API, Vue Router & Pinia</p>
    </footer>
  </div>
</template>

<script setup>
import { RouterView } from 'vue-router';
import Header from './components/Header.vue';
</script>

// Module2_FrontendDev/handson_10/src/App.jsx
import React from 'react';
import { Routes, Route } from 'react-router-dom';
import Header from './components/Header';
import CoursesPage from './pages/CoursesPage';
import ProfilePage from './pages/ProfilePage';

const App = () => {
  return (
    <div className="app">
      <Header />
      <main>
        <Routes>
          <Route path="/" element={<CoursesPage />} />
          <Route path="/profile" element={<ProfilePage />} />
        </Routes>
      </main>
      <footer className="site-footer">
        <p>&copy; 2026 Student Portal | Centralized Axios API & Advanced State Management</p>
      </footer>
    </div>
  );
};

export default App;
