// Module2_FrontendDev/handson_07/src/app/components/course-card/course-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-course-card',
  template: `
    <article class="course-card">
      <div class="card-header">
        <span class="course-code">{{ code }}</span>
        <span class="course-credits">{{ credits }} Credits</span>
      </div>
      <h3 style="font-size: 1.1rem; color: #0f172a; margin-bottom: 0.5rem;">{{ name }}</h3>
      <p style="font-weight: 600; color: #059669; font-size: 0.9rem;">Target Grade: {{ grade }}</p>
    </article>
  `
})
export class CourseCardComponent {
  @Input() name: string = '';
  @Input() code: string = '';
  @Input() credits: number = 0;
  @Input() grade: string = '';
}

// Module2_FrontendDev/handson_08/src/components/CourseCard.vue
<template>
  <article class="course-card">
    <div class="card-header">
      <span class="code-badge">{{ code }}</span>
      <span class="credits-badge">{{ credits }} Credits</span>
    </div>
    <h3 style="font-size: 1.15rem; color: #0f172a; margin-bottom: 0.5rem;">{{ name }}</h3>
    <p style="font-size: 0.9rem; color: #64748b; margin-bottom: 1rem;">Target Grade: {{ grade }}</p>
    <slot name="actions"></slot>
  </article>
</template>

<script setup>
// Define component props (Task 108)
defineProps({
  id: Number,
  name: String,
  code: String,
  credits: Number,
  grade: String
});
</script>

<style scoped>
/* Component scoped styles */
</style>
