// Module2_FrontendDev/handson_06/src/components/Header.jsx
import React from 'react';
import { Link, NavLink } from 'react-router-dom';
import { useSelector } from 'react-redux';

/**
 * Header Component with React Router Links and Redux State (Task 78, 89)
 */
const Header = () => {
  // Read state directly from Redux Store via useSelector selector
  const enrolledCourses = useSelector(state => state.enrollment.enrolledCourses);

  return (
    <header className="site-header">
      <h1>
        <Link to="/">Student Portal</Link>
      </h1>
      <nav className="nav-links">
        <NavLink to="/" className={({ isActive }) => (isActive ? 'nav-link active' : 'nav-link')}>
          Home
        </NavLink>
        <NavLink to="/courses" className={({ isActive }) => (isActive ? 'nav-link active' : 'nav-link')}>
          Courses
        </NavLink>
        <NavLink to="/profile" className={({ isActive }) => (isActive ? 'nav-link active' : 'nav-link')}>
          Profile
        </NavLink>
        <span className="badge">Enrolled: {enrolledCourses.length}</span>
      </nav>
    </header>
  );
};

export default Header;

// Module2_FrontendDev/handson_08/src/components/Header.vue
<template>
  <header class="site-header">
    <RouterLink to="/" class="site-title">Student Portal (Vue 3)</RouterLink>
    <nav class="nav-links">
      <RouterLink to="/" class="nav-link">Home</RouterLink>
      <RouterLink to="/courses" class="nav-link">Courses</RouterLink>
      <RouterLink to="/profile" class="nav-link">Profile</RouterLink>
      <!-- Display enrolled count from Pinia Store (Task 120) -->
      <span class="badge">Enrolled: {{ enrollmentStore.enrolledCourses.length }}</span>
    </nav>
  </header>
</template>

<script setup>
import { RouterLink } from 'vue-router';
import { useEnrollmentStore } from '../stores/enrollment';

const enrollmentStore = useEnrollmentStore();
</script>

<style scoped>
/* Component scoped styles */
</style>
