// Module2_FrontendDev/handson_08/src/App.vue
<template>
  <div class="app-container">
    <Header />
    <main>
      <!-- Task 113: RouterView Outlet -->
      <RouterView />
    </main>
    <footer class="site-footer">
      <p>&copy; 2026 Student Portal Vue 3 Application | Composition API, Vue Router & Pinia</p>
    </footer>
  </div>
</template>

<script setup>
import { RouterView } from 'vue-router';
import Header from './components/Header.vue';
</script>

// Module2_FrontendDev/handson_07/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  title = 'student-portal-angular';
}

<!-- Header Component -->
<app-header></app-header>

<!-- Router Outlet for Navigation Views (Task 102) -->
<main>
  <router-outlet></router-outlet>
</main>

<!-- Footer -->
<footer class="site-footer">
  <p>&copy; 2026 Student Portal Angular Application | Angular Router & Reactive Forms</p>
</footer>
