// Module2_FrontendDev/handson_08/src/App.vue
<template>
  <div class="app-container">
    <Header />
    <main>
      <!-- Task 113: RouterView Outlet -->
      <RouterView />
    </main>
    <footer class="site-footer">
      <p>&copy; 2026 Student Portal Vue 3 Application | Composition API, Vue Router & Pinia</p>
    </footer>
  </div>
</template>

<script setup>
import { RouterView } from 'vue-router';
import Header from './components/Header.vue';
</script>

// Module2_FrontendDev/handson_06/src/App.jsx
import React from 'react';
import { Routes, Route } from 'react-router-dom';
import Header from './components/Header';
import HomePage from './pages/HomePage';
import CoursesPage from './pages/CoursesPage';
import CourseDetailPage from './pages/CourseDetailPage';
import ProfilePage from './pages/ProfilePage';

/**
 * App Component defining React Router Routes (Task 77)
 */
const App = () => {
  return (
    <div className="app">
      <Header />
      <main>
        <Routes>
          <Route path="/" element={<HomePage />} />
          <Route path="/courses" element={<CoursesPage />} />
          <Route path="/courses/:courseId" element={<CourseDetailPage />} />
          <Route path="/profile" element={<ProfilePage />} />
        </Routes>
      </main>
      <footer className="site-footer">
        <p>&copy; 2026 Student Portal React SPA | React Router v6 & Redux Toolkit</p>
      </footer>
    </div>
  );
};

export default App;
