// Module2_FrontendDev/handson_08/src/components/Header.vue
<template>
  <header class="site-header">
    <RouterLink to="/" class="site-title">Student Portal (Vue 3)</RouterLink>
    <nav class="nav-links">
      <RouterLink to="/" class="nav-link">Home</RouterLink>
      <RouterLink to="/courses" class="nav-link">Courses</RouterLink>
      <RouterLink to="/profile" class="nav-link">Profile</RouterLink>
      <!-- Display enrolled count from Pinia Store (Task 120) -->
      <span class="badge">Enrolled: {{ enrollmentStore.enrolledCourses.length }}</span>
    </nav>
  </header>
</template>

<script setup>
import { RouterLink } from 'vue-router';
import { useEnrollmentStore } from '../stores/enrollment';

const enrollmentStore = useEnrollmentStore();
</script>

<style scoped>
/* Component scoped styles */
</style>

// Module2_FrontendDev/handson_10/src/components/Header.jsx
import React from 'react';
import { Link, NavLink } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { selectEnrolledCourses } from '../store/coursesSlice';

const Header = () => {
  const enrolledCourses = useSelector(selectEnrolledCourses);

  return (
    <header className="site-header">
      <Link to="/" className="site-title">Student Portal (Central API)</Link>
      <nav className="nav-links">
        <NavLink to="/" className={({ isActive }) => (isActive ? 'nav-link active' : 'nav-link')}>
          Courses
        </NavLink>
        <NavLink to="/profile" className={({ isActive }) => (isActive ? 'nav-link active' : 'nav-link')}>
          Profile ({enrolledCourses.length})
        </NavLink>
      </nav>
    </header>
  );
};

export default Header;
