// Module2_FrontendDev/handson_10/src/components/Header.jsx
import React from 'react';
import { Link, NavLink } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { selectEnrolledCourses } from '../store/coursesSlice';

const Header = () => {
  const enrolledCourses = useSelector(selectEnrolledCourses);

  return (
    <header className="site-header">
      <Link to="/" className="site-title">Student Portal (Central API)</Link>
      <nav className="nav-links">
        <NavLink to="/" className={({ isActive }) => (isActive ? 'nav-link active' : 'nav-link')}>
          Courses
        </NavLink>
        <NavLink to="/profile" className={({ isActive }) => (isActive ? 'nav-link active' : 'nav-link')}>
          Profile ({enrolledCourses.length})
        </NavLink>
      </nav>
    </header>
  );
};

export default Header;

// Module2_FrontendDev/handson_07/src/app/components/header/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  template: `
    <header class="site-header">
      <a routerLink="/" class="site-title">Student Portal (Angular)</a>
      <nav class="nav-links">
        <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">Courses</a>
        <a routerLink="/profile" routerLinkActive="active">Student Profile</a>
      </nav>
    </header>
  `
})
export class HeaderComponent {}
