// Module2_FrontendDev/handson_05/src/components/CourseCard.jsx
import React from 'react';

/**
 * Functional CourseCard component receiving props
 * Tasks 65 & 69
 */
const CourseCard = ({ id, name, code, credits, grade, onEnroll }) => {
  return (
    <article className="course-card">
      <div className="card-header">
        <span className="course-code">{code}</span>
        <span className="course-credits">{credits} Credits</span>
      </div>
      <h3 className="course-name">{name}</h3>
      <div className="card-footer">
        <span className="grade">Grade: {grade}</span>
        <button 
          className="btn-enroll" 
          onClick={() => onEnroll({ id, name, code, credits, grade })}
        >
          Enroll
        </button>
      </div>
    </article>
  );
};

export default CourseCard;

// Module2_FrontendDev/handson_07/src/app/components/course-card/course-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-course-card',
  template: `
    <article class="course-card">
      <div class="card-header">
        <span class="course-code">{{ code }}</span>
        <span class="course-credits">{{ credits }} Credits</span>
      </div>
      <h3 style="font-size: 1.1rem; color: #0f172a; margin-bottom: 0.5rem;">{{ name }}</h3>
      <p style="font-weight: 600; color: #059669; font-size: 0.9rem;">Target Grade: {{ grade }}</p>
    </article>
  `
})
export class CourseCardComponent {
  @Input() name: string = '';
  @Input() code: string = '';
  @Input() credits: number = 0;
  @Input() grade: string = '';
}
